name: internal_ssh_integration
description: Help developers generate ssh keys and directions on how to use them to interact with the hubtel internal sdk's
version: 1.0.0
homepage: https://github.com/hubtel/internal_ssh_integration

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
